name = "BCBIRegistry"
uuid = "26a550a3-39fe-4af4-af6d-e8814c2b6dd9"
repo = "https://github.com/bcbi/BCBIRegistry.git"

description = """
Official package registry for the Brown Center for Biomedical Informatics.
"""

[packages]
d14d998a-9e6b-11e8-16d3-6f2879ea456d = { name = "PredictMDExtra", path = "packages/P/PredictMDExtra" }
